---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-cloudfront-writer
  namespace: default
rules:
- apiGroups:
  - cloudfront.services.k8s.aws
  resources:
  - cachepolicies
  - distributions
  - functions
  - originaccesscontrols
  - originrequestpolicies
  - responseheaderspolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudfront.services.k8s.aws
  resources:
  - cachepolicies
  - distributions
  - functions
  - originaccesscontrols
  - originrequestpolicies
  - responseheaderspolicies
  verbs:
  - get
  - patch
  - update
