// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package connection_group

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AnycastIPListID, b.ko.Spec.AnycastIPListID) {
		delta.Add("Spec.AnycastIPListID", a.ko.Spec.AnycastIPListID, b.ko.Spec.AnycastIPListID)
	} else if a.ko.Spec.AnycastIPListID != nil && b.ko.Spec.AnycastIPListID != nil {
		if *a.ko.Spec.AnycastIPListID != *b.ko.Spec.AnycastIPListID {
			delta.Add("Spec.AnycastIPListID", a.ko.Spec.AnycastIPListID, b.ko.Spec.AnycastIPListID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Enabled, b.ko.Spec.Enabled) {
		delta.Add("Spec.Enabled", a.ko.Spec.Enabled, b.ko.Spec.Enabled)
	} else if a.ko.Spec.Enabled != nil && b.ko.Spec.Enabled != nil {
		if *a.ko.Spec.Enabled != *b.ko.Spec.Enabled {
			delta.Add("Spec.Enabled", a.ko.Spec.Enabled, b.ko.Spec.Enabled)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.IPv6Enabled, b.ko.Spec.IPv6Enabled) {
		delta.Add("Spec.IPv6Enabled", a.ko.Spec.IPv6Enabled, b.ko.Spec.IPv6Enabled)
	} else if a.ko.Spec.IPv6Enabled != nil && b.ko.Spec.IPv6Enabled != nil {
		if *a.ko.Spec.IPv6Enabled != *b.ko.Spec.IPv6Enabled {
			delta.Add("Spec.IPv6Enabled", a.ko.Spec.IPv6Enabled, b.ko.Spec.IPv6Enabled)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
