# This configuration is a placeholder. Replace any values with relevant values for your
# service controller project.
---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS CloudFront controller is a service controller for managing CloudFront resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon CloudFront
description: |-
  Manage Amazon CloudFront resources in AWS from within your Kubernetes cluster.


  **About Amazon CloudFront**


  Amazon CloudFront is a web service that speeds up distribution of your static and dynamic web content, such as .html, .css, .js, and image files, to your users. CloudFront delivers your content through a worldwide network of data centers called edge locations.


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.
samples:
- kind: CachePolicy
  spec: '{}'
- kind: Function
  spec: '{}'
- kind: Distribution
  spec: '{}'
maintainers:
- name: "cloudfront maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon CloudFront Developer Resources
  url: https://aws.amazon.com/cloudfront/developer-resources/
