// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package origin_access_control

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.OriginAccessControlConfig, b.ko.Spec.OriginAccessControlConfig) {
		delta.Add("Spec.OriginAccessControlConfig", a.ko.Spec.OriginAccessControlConfig, b.ko.Spec.OriginAccessControlConfig)
	} else if a.ko.Spec.OriginAccessControlConfig != nil && b.ko.Spec.OriginAccessControlConfig != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.OriginAccessControlConfig.Description, b.ko.Spec.OriginAccessControlConfig.Description) {
			delta.Add("Spec.OriginAccessControlConfig.Description", a.ko.Spec.OriginAccessControlConfig.Description, b.ko.Spec.OriginAccessControlConfig.Description)
		} else if a.ko.Spec.OriginAccessControlConfig.Description != nil && b.ko.Spec.OriginAccessControlConfig.Description != nil {
			if *a.ko.Spec.OriginAccessControlConfig.Description != *b.ko.Spec.OriginAccessControlConfig.Description {
				delta.Add("Spec.OriginAccessControlConfig.Description", a.ko.Spec.OriginAccessControlConfig.Description, b.ko.Spec.OriginAccessControlConfig.Description)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OriginAccessControlConfig.Name, b.ko.Spec.OriginAccessControlConfig.Name) {
			delta.Add("Spec.OriginAccessControlConfig.Name", a.ko.Spec.OriginAccessControlConfig.Name, b.ko.Spec.OriginAccessControlConfig.Name)
		} else if a.ko.Spec.OriginAccessControlConfig.Name != nil && b.ko.Spec.OriginAccessControlConfig.Name != nil {
			if *a.ko.Spec.OriginAccessControlConfig.Name != *b.ko.Spec.OriginAccessControlConfig.Name {
				delta.Add("Spec.OriginAccessControlConfig.Name", a.ko.Spec.OriginAccessControlConfig.Name, b.ko.Spec.OriginAccessControlConfig.Name)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OriginAccessControlConfig.OriginAccessControlOriginType, b.ko.Spec.OriginAccessControlConfig.OriginAccessControlOriginType) {
			delta.Add("Spec.OriginAccessControlConfig.OriginAccessControlOriginType", a.ko.Spec.OriginAccessControlConfig.OriginAccessControlOriginType, b.ko.Spec.OriginAccessControlConfig.OriginAccessControlOriginType)
		} else if a.ko.Spec.OriginAccessControlConfig.OriginAccessControlOriginType != nil && b.ko.Spec.OriginAccessControlConfig.OriginAccessControlOriginType != nil {
			if *a.ko.Spec.OriginAccessControlConfig.OriginAccessControlOriginType != *b.ko.Spec.OriginAccessControlConfig.OriginAccessControlOriginType {
				delta.Add("Spec.OriginAccessControlConfig.OriginAccessControlOriginType", a.ko.Spec.OriginAccessControlConfig.OriginAccessControlOriginType, b.ko.Spec.OriginAccessControlConfig.OriginAccessControlOriginType)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OriginAccessControlConfig.SigningBehavior, b.ko.Spec.OriginAccessControlConfig.SigningBehavior) {
			delta.Add("Spec.OriginAccessControlConfig.SigningBehavior", a.ko.Spec.OriginAccessControlConfig.SigningBehavior, b.ko.Spec.OriginAccessControlConfig.SigningBehavior)
		} else if a.ko.Spec.OriginAccessControlConfig.SigningBehavior != nil && b.ko.Spec.OriginAccessControlConfig.SigningBehavior != nil {
			if *a.ko.Spec.OriginAccessControlConfig.SigningBehavior != *b.ko.Spec.OriginAccessControlConfig.SigningBehavior {
				delta.Add("Spec.OriginAccessControlConfig.SigningBehavior", a.ko.Spec.OriginAccessControlConfig.SigningBehavior, b.ko.Spec.OriginAccessControlConfig.SigningBehavior)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OriginAccessControlConfig.SigningProtocol, b.ko.Spec.OriginAccessControlConfig.SigningProtocol) {
			delta.Add("Spec.OriginAccessControlConfig.SigningProtocol", a.ko.Spec.OriginAccessControlConfig.SigningProtocol, b.ko.Spec.OriginAccessControlConfig.SigningProtocol)
		} else if a.ko.Spec.OriginAccessControlConfig.SigningProtocol != nil && b.ko.Spec.OriginAccessControlConfig.SigningProtocol != nil {
			if *a.ko.Spec.OriginAccessControlConfig.SigningProtocol != *b.ko.Spec.OriginAccessControlConfig.SigningProtocol {
				delta.Add("Spec.OriginAccessControlConfig.SigningProtocol", a.ko.Spec.OriginAccessControlConfig.SigningProtocol, b.ko.Spec.OriginAccessControlConfig.SigningProtocol)
			}
		}
	}

	return delta
}
