// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package response_headers_policy

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig, b.ko.Spec.ResponseHeadersPolicyConfig) {
		delta.Add("Spec.ResponseHeadersPolicyConfig", a.ko.Spec.ResponseHeadersPolicyConfig, b.ko.Spec.ResponseHeadersPolicyConfig)
	} else if a.ko.Spec.ResponseHeadersPolicyConfig != nil && b.ko.Spec.ResponseHeadersPolicyConfig != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.Comment, b.ko.Spec.ResponseHeadersPolicyConfig.Comment) {
			delta.Add("Spec.ResponseHeadersPolicyConfig.Comment", a.ko.Spec.ResponseHeadersPolicyConfig.Comment, b.ko.Spec.ResponseHeadersPolicyConfig.Comment)
		} else if a.ko.Spec.ResponseHeadersPolicyConfig.Comment != nil && b.ko.Spec.ResponseHeadersPolicyConfig.Comment != nil {
			if *a.ko.Spec.ResponseHeadersPolicyConfig.Comment != *b.ko.Spec.ResponseHeadersPolicyConfig.Comment {
				delta.Add("Spec.ResponseHeadersPolicyConfig.Comment", a.ko.Spec.ResponseHeadersPolicyConfig.Comment, b.ko.Spec.ResponseHeadersPolicyConfig.Comment)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig) {
			delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig)
		} else if a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig != nil && b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowCredentials, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowCredentials) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowCredentials", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowCredentials, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowCredentials)
			} else if a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowCredentials != nil && b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowCredentials != nil {
				if *a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowCredentials != *b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowCredentials {
					delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowCredentials", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowCredentials, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowCredentials)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders)
			} else if a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders != nil && b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders != nil {
				if len(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders.Items) != len(b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders.Items) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders.Items", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders.Items, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders.Items)
				} else if len(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders.Items) > 0 {
					if !ackcompare.SliceStringPEqual(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders.Items, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders.Items) {
						delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders.Items", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders.Items, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowHeaders.Items)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods)
			} else if a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods != nil && b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods != nil {
				if len(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods.Items) != len(b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods.Items) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods.Items", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods.Items, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods.Items)
				} else if len(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods.Items) > 0 {
					if !ackcompare.SliceStringPEqual(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods.Items, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods.Items) {
						delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods.Items", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods.Items, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowMethods.Items)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins)
			} else if a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins != nil && b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins != nil {
				if len(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins.Items) != len(b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins.Items) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins.Items", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins.Items, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins.Items)
				} else if len(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins.Items) > 0 {
					if !ackcompare.SliceStringPEqual(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins.Items, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins.Items) {
						delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins.Items", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins.Items, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlAllowOrigins.Items)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders)
			} else if a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders != nil && b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders != nil {
				if len(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders.Items) != len(b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders.Items) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders.Items", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders.Items, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders.Items)
				} else if len(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders.Items) > 0 {
					if !ackcompare.SliceStringPEqual(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders.Items, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders.Items) {
						delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders.Items", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders.Items, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlExposeHeaders.Items)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlMaxAgeSec, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlMaxAgeSec) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlMaxAgeSec", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlMaxAgeSec, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlMaxAgeSec)
			} else if a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlMaxAgeSec != nil && b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlMaxAgeSec != nil {
				if *a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlMaxAgeSec != *b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlMaxAgeSec {
					delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlMaxAgeSec", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlMaxAgeSec, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.AccessControlMaxAgeSec)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.OriginOverride, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.OriginOverride) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.OriginOverride", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.OriginOverride, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.OriginOverride)
			} else if a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.OriginOverride != nil && b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.OriginOverride != nil {
				if *a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.OriginOverride != *b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.OriginOverride {
					delta.Add("Spec.ResponseHeadersPolicyConfig.CORSConfig.OriginOverride", a.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.OriginOverride, b.ko.Spec.ResponseHeadersPolicyConfig.CORSConfig.OriginOverride)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig, b.ko.Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig) {
			delta.Add("Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig", a.ko.Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig, b.ko.Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig)
		} else if a.ko.Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig != nil && b.ko.Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig != nil {
			if len(a.ko.Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig.Items) != len(b.ko.Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig.Items) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig.Items", a.ko.Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig.Items, b.ko.Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig.Items)
			} else if len(a.ko.Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig.Items) > 0 {
				if !reflect.DeepEqual(a.ko.Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig.Items, b.ko.Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig.Items) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig.Items", a.ko.Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig.Items, b.ko.Spec.ResponseHeadersPolicyConfig.CustomHeadersConfig.Items)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.Name, b.ko.Spec.ResponseHeadersPolicyConfig.Name) {
			delta.Add("Spec.ResponseHeadersPolicyConfig.Name", a.ko.Spec.ResponseHeadersPolicyConfig.Name, b.ko.Spec.ResponseHeadersPolicyConfig.Name)
		} else if a.ko.Spec.ResponseHeadersPolicyConfig.Name != nil && b.ko.Spec.ResponseHeadersPolicyConfig.Name != nil {
			if *a.ko.Spec.ResponseHeadersPolicyConfig.Name != *b.ko.Spec.ResponseHeadersPolicyConfig.Name {
				delta.Add("Spec.ResponseHeadersPolicyConfig.Name", a.ko.Spec.ResponseHeadersPolicyConfig.Name, b.ko.Spec.ResponseHeadersPolicyConfig.Name)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig, b.ko.Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig) {
			delta.Add("Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig", a.ko.Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig, b.ko.Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig)
		} else if a.ko.Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig != nil && b.ko.Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig != nil {
			if len(a.ko.Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig.Items) != len(b.ko.Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig.Items) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig.Items", a.ko.Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig.Items, b.ko.Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig.Items)
			} else if len(a.ko.Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig.Items) > 0 {
				if !reflect.DeepEqual(a.ko.Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig.Items, b.ko.Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig.Items) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig.Items", a.ko.Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig.Items, b.ko.Spec.ResponseHeadersPolicyConfig.RemoveHeadersConfig.Items)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig) {
			delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig)
		} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy)
			} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.ContentSecurityPolicy, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.ContentSecurityPolicy) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.ContentSecurityPolicy", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.ContentSecurityPolicy, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.ContentSecurityPolicy)
				} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.ContentSecurityPolicy != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.ContentSecurityPolicy != nil {
					if *a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.ContentSecurityPolicy != *b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.ContentSecurityPolicy {
						delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.ContentSecurityPolicy", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.ContentSecurityPolicy, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.ContentSecurityPolicy)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.Override) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.Override", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.Override)
				} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.Override != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.Override != nil {
					if *a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.Override != *b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.Override {
						delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.Override", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.Override)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions)
			} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions.Override) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions.Override", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions.Override)
				} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions.Override != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions.Override != nil {
					if *a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions.Override != *b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions.Override {
						delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions.Override", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions.Override)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions)
			} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.FrameOption, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.FrameOption) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.FrameOption", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.FrameOption, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.FrameOption)
				} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.FrameOption != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.FrameOption != nil {
					if *a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.FrameOption != *b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.FrameOption {
						delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.FrameOption", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.FrameOption, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.FrameOption)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.Override) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.Override", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.Override)
				} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.Override != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.Override != nil {
					if *a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.Override != *b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.Override {
						delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.Override", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.Override)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy)
			} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.Override) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.Override", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.Override)
				} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.Override != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.Override != nil {
					if *a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.Override != *b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.Override {
						delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.Override", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.Override)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.ReferrerPolicy, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.ReferrerPolicy) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.ReferrerPolicy", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.ReferrerPolicy, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.ReferrerPolicy)
				} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.ReferrerPolicy != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.ReferrerPolicy != nil {
					if *a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.ReferrerPolicy != *b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.ReferrerPolicy {
						delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.ReferrerPolicy", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.ReferrerPolicy, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.ReferrerPolicy)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity)
			} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.AccessControlMaxAgeSec, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.AccessControlMaxAgeSec) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.AccessControlMaxAgeSec", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.AccessControlMaxAgeSec, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.AccessControlMaxAgeSec)
				} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.AccessControlMaxAgeSec != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.AccessControlMaxAgeSec != nil {
					if *a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.AccessControlMaxAgeSec != *b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.AccessControlMaxAgeSec {
						delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.AccessControlMaxAgeSec", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.AccessControlMaxAgeSec, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.AccessControlMaxAgeSec)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.IncludeSubdomains, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.IncludeSubdomains) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.IncludeSubdomains", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.IncludeSubdomains, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.IncludeSubdomains)
				} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.IncludeSubdomains != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.IncludeSubdomains != nil {
					if *a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.IncludeSubdomains != *b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.IncludeSubdomains {
						delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.IncludeSubdomains", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.IncludeSubdomains, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.IncludeSubdomains)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Override) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Override", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Override)
				} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Override != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Override != nil {
					if *a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Override != *b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Override {
						delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Override", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Override)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Preload, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Preload) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Preload", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Preload, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Preload)
				} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Preload != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Preload != nil {
					if *a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Preload != *b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Preload {
						delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Preload", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Preload, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Preload)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection)
			} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ModeBlock, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ModeBlock) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ModeBlock", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ModeBlock, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ModeBlock)
				} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ModeBlock != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ModeBlock != nil {
					if *a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ModeBlock != *b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ModeBlock {
						delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ModeBlock", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ModeBlock, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ModeBlock)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Override) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Override", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Override)
				} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Override != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Override != nil {
					if *a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Override != *b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Override {
						delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Override", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Override, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Override)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Protection, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Protection) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Protection", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Protection, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Protection)
				} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Protection != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Protection != nil {
					if *a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Protection != *b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Protection {
						delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Protection", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Protection, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Protection)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ReportURI, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ReportURI) {
					delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ReportURI", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ReportURI, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ReportURI)
				} else if a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ReportURI != nil && b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ReportURI != nil {
					if *a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ReportURI != *b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ReportURI {
						delta.Add("Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ReportURI", a.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ReportURI, b.ko.Spec.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ReportURI)
					}
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig, b.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig) {
			delta.Add("Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig", a.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig, b.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig)
		} else if a.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig != nil && b.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.Enabled, b.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.Enabled) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.Enabled", a.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.Enabled, b.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.Enabled)
			} else if a.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.Enabled != nil && b.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.Enabled != nil {
				if *a.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.Enabled != *b.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.Enabled {
					delta.Add("Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.Enabled", a.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.Enabled, b.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.Enabled)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.SamplingRate, b.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.SamplingRate) {
				delta.Add("Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.SamplingRate", a.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.SamplingRate, b.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.SamplingRate)
			} else if a.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.SamplingRate != nil && b.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.SamplingRate != nil {
				if *a.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.SamplingRate != *b.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.SamplingRate {
					delta.Add("Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.SamplingRate", a.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.SamplingRate, b.ko.Spec.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.SamplingRate)
				}
			}
		}
	}

	return delta
}
