// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package cache_policy

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/cloudfront"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/cloudfront-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.CloudFront{}
	_ = &svcapitypes.CachePolicy{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetCachePolicyOutput
	resp, err = rm.sdkapi.GetCachePolicyWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetCachePolicy", err)
	if err != nil {
		if reqErr, ok := ackerr.AWSRequestFailure(err); ok && reqErr.StatusCode() == 404 {
			return nil, ackerr.NotFound
		}
		if awsErr, ok := ackerr.AWSError(err); ok && awsErr.Code() == "NoSuchCachePolicy" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.CachePolicy.CachePolicyConfig != nil {
		f0 := &svcapitypes.CachePolicyConfig{}
		if resp.CachePolicy.CachePolicyConfig.Comment != nil {
			f0.Comment = resp.CachePolicy.CachePolicyConfig.Comment
		}
		if resp.CachePolicy.CachePolicyConfig.DefaultTTL != nil {
			f0.DefaultTTL = resp.CachePolicy.CachePolicyConfig.DefaultTTL
		}
		if resp.CachePolicy.CachePolicyConfig.MaxTTL != nil {
			f0.MaxTTL = resp.CachePolicy.CachePolicyConfig.MaxTTL
		}
		if resp.CachePolicy.CachePolicyConfig.MinTTL != nil {
			f0.MinTTL = resp.CachePolicy.CachePolicyConfig.MinTTL
		}
		if resp.CachePolicy.CachePolicyConfig.Name != nil {
			f0.Name = resp.CachePolicy.CachePolicyConfig.Name
		}
		if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin != nil {
			f0f5 := &svcapitypes.ParametersInCacheKeyAndForwardedToOrigin{}
			if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig != nil {
				f0f5f0 := &svcapitypes.CachePolicyCookiesConfig{}
				if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.CookieBehavior != nil {
					f0f5f0.CookieBehavior = resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.CookieBehavior
				}
				if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.Cookies != nil {
					f0f5f0f1 := &svcapitypes.CookieNames{}
					if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.Cookies.Items != nil {
						f0f5f0f1f0 := []*string{}
						for _, f0f5f0f1f0iter := range resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.Cookies.Items {
							var f0f5f0f1f0elem string
							f0f5f0f1f0elem = *f0f5f0f1f0iter
							f0f5f0f1f0 = append(f0f5f0f1f0, &f0f5f0f1f0elem)
						}
						f0f5f0f1.Items = f0f5f0f1f0
					}
					f0f5f0.Cookies = f0f5f0f1
				}
				f0f5.CookiesConfig = f0f5f0
			}
			if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingBrotli != nil {
				f0f5.EnableAcceptEncodingBrotli = resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingBrotli
			}
			if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingGzip != nil {
				f0f5.EnableAcceptEncodingGzip = resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingGzip
			}
			if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig != nil {
				f0f5f3 := &svcapitypes.CachePolicyHeadersConfig{}
				if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.HeaderBehavior != nil {
					f0f5f3.HeaderBehavior = resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.HeaderBehavior
				}
				if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.Headers != nil {
					f0f5f3f1 := &svcapitypes.Headers{}
					if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.Headers.Items != nil {
						f0f5f3f1f0 := []*string{}
						for _, f0f5f3f1f0iter := range resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.Headers.Items {
							var f0f5f3f1f0elem string
							f0f5f3f1f0elem = *f0f5f3f1f0iter
							f0f5f3f1f0 = append(f0f5f3f1f0, &f0f5f3f1f0elem)
						}
						f0f5f3f1.Items = f0f5f3f1f0
					}
					f0f5f3.Headers = f0f5f3f1
				}
				f0f5.HeadersConfig = f0f5f3
			}
			if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig != nil {
				f0f5f4 := &svcapitypes.CachePolicyQueryStringsConfig{}
				if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStringBehavior != nil {
					f0f5f4.QueryStringBehavior = resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStringBehavior
				}
				if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStrings != nil {
					f0f5f4f1 := &svcapitypes.QueryStringNames{}
					if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStrings.Items != nil {
						f0f5f4f1f0 := []*string{}
						for _, f0f5f4f1f0iter := range resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStrings.Items {
							var f0f5f4f1f0elem string
							f0f5f4f1f0elem = *f0f5f4f1f0iter
							f0f5f4f1f0 = append(f0f5f4f1f0, &f0f5f4f1f0elem)
						}
						f0f5f4f1.Items = f0f5f4f1f0
					}
					f0f5f4.QueryStrings = f0f5f4f1
				}
				f0f5.QueryStringsConfig = f0f5f4
			}
			f0.ParametersInCacheKeyAndForwardedToOrigin = f0f5
		}
		ko.Spec.CachePolicyConfig = f0
	} else {
		ko.Spec.CachePolicyConfig = nil
	}
	if resp.CachePolicy.Id != nil {
		ko.Status.ID = resp.CachePolicy.Id
	} else {
		ko.Status.ID = nil
	}
	if resp.CachePolicy.LastModifiedTime != nil {
		ko.Status.LastModifiedTime = &metav1.Time{*resp.CachePolicy.LastModifiedTime}
	} else {
		ko.Status.LastModifiedTime = nil
	}

	rm.setStatusDefaults(ko)
	// We need to do this manually because the ETag field (required for the
	// IfMatch field when updating or deleting a resource in CloudFront) is
	// outside the wrapper field of `CachePolicy` in the response and therefore
	// not picked up by SetResource code generation.
	if resp.ETag != nil {
		ko.Status.ETag = resp.ETag
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.ID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetCachePolicyInput, error) {
	res := &svcsdk.GetCachePolicyInput{}

	if r.ko.Status.ID != nil {
		res.SetId(*r.ko.Status.ID)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}
	// ¯\\\_(ツ)_/¯
	setQuantityFields(input.CachePolicyConfig)

	var resp *svcsdk.CreateCachePolicyOutput
	_ = resp
	resp, err = rm.sdkapi.CreateCachePolicyWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateCachePolicy", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.CachePolicy.CachePolicyConfig != nil {
		f0 := &svcapitypes.CachePolicyConfig{}
		if resp.CachePolicy.CachePolicyConfig.Comment != nil {
			f0.Comment = resp.CachePolicy.CachePolicyConfig.Comment
		}
		if resp.CachePolicy.CachePolicyConfig.DefaultTTL != nil {
			f0.DefaultTTL = resp.CachePolicy.CachePolicyConfig.DefaultTTL
		}
		if resp.CachePolicy.CachePolicyConfig.MaxTTL != nil {
			f0.MaxTTL = resp.CachePolicy.CachePolicyConfig.MaxTTL
		}
		if resp.CachePolicy.CachePolicyConfig.MinTTL != nil {
			f0.MinTTL = resp.CachePolicy.CachePolicyConfig.MinTTL
		}
		if resp.CachePolicy.CachePolicyConfig.Name != nil {
			f0.Name = resp.CachePolicy.CachePolicyConfig.Name
		}
		if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin != nil {
			f0f5 := &svcapitypes.ParametersInCacheKeyAndForwardedToOrigin{}
			if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig != nil {
				f0f5f0 := &svcapitypes.CachePolicyCookiesConfig{}
				if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.CookieBehavior != nil {
					f0f5f0.CookieBehavior = resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.CookieBehavior
				}
				if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.Cookies != nil {
					f0f5f0f1 := &svcapitypes.CookieNames{}
					if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.Cookies.Items != nil {
						f0f5f0f1f0 := []*string{}
						for _, f0f5f0f1f0iter := range resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.Cookies.Items {
							var f0f5f0f1f0elem string
							f0f5f0f1f0elem = *f0f5f0f1f0iter
							f0f5f0f1f0 = append(f0f5f0f1f0, &f0f5f0f1f0elem)
						}
						f0f5f0f1.Items = f0f5f0f1f0
					}
					f0f5f0.Cookies = f0f5f0f1
				}
				f0f5.CookiesConfig = f0f5f0
			}
			if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingBrotli != nil {
				f0f5.EnableAcceptEncodingBrotli = resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingBrotli
			}
			if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingGzip != nil {
				f0f5.EnableAcceptEncodingGzip = resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingGzip
			}
			if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig != nil {
				f0f5f3 := &svcapitypes.CachePolicyHeadersConfig{}
				if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.HeaderBehavior != nil {
					f0f5f3.HeaderBehavior = resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.HeaderBehavior
				}
				if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.Headers != nil {
					f0f5f3f1 := &svcapitypes.Headers{}
					if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.Headers.Items != nil {
						f0f5f3f1f0 := []*string{}
						for _, f0f5f3f1f0iter := range resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.Headers.Items {
							var f0f5f3f1f0elem string
							f0f5f3f1f0elem = *f0f5f3f1f0iter
							f0f5f3f1f0 = append(f0f5f3f1f0, &f0f5f3f1f0elem)
						}
						f0f5f3f1.Items = f0f5f3f1f0
					}
					f0f5f3.Headers = f0f5f3f1
				}
				f0f5.HeadersConfig = f0f5f3
			}
			if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig != nil {
				f0f5f4 := &svcapitypes.CachePolicyQueryStringsConfig{}
				if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStringBehavior != nil {
					f0f5f4.QueryStringBehavior = resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStringBehavior
				}
				if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStrings != nil {
					f0f5f4f1 := &svcapitypes.QueryStringNames{}
					if resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStrings.Items != nil {
						f0f5f4f1f0 := []*string{}
						for _, f0f5f4f1f0iter := range resp.CachePolicy.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStrings.Items {
							var f0f5f4f1f0elem string
							f0f5f4f1f0elem = *f0f5f4f1f0iter
							f0f5f4f1f0 = append(f0f5f4f1f0, &f0f5f4f1f0elem)
						}
						f0f5f4f1.Items = f0f5f4f1f0
					}
					f0f5f4.QueryStrings = f0f5f4f1
				}
				f0f5.QueryStringsConfig = f0f5f4
			}
			f0.ParametersInCacheKeyAndForwardedToOrigin = f0f5
		}
		ko.Spec.CachePolicyConfig = f0
	} else {
		ko.Spec.CachePolicyConfig = nil
	}
	if resp.CachePolicy.Id != nil {
		ko.Status.ID = resp.CachePolicy.Id
	} else {
		ko.Status.ID = nil
	}
	if resp.CachePolicy.LastModifiedTime != nil {
		ko.Status.LastModifiedTime = &metav1.Time{*resp.CachePolicy.LastModifiedTime}
	} else {
		ko.Status.LastModifiedTime = nil
	}

	rm.setStatusDefaults(ko)
	// We need to do this manually because the ETag field (required for the
	// IfMatch field when updating or deleting a resource in CloudFront) is
	// outside the wrapper field of `CachePolicy` in the response and therefore
	// not picked up by SetResource code generation.
	if resp.ETag != nil {
		ko.Status.ETag = resp.ETag
	}

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateCachePolicyInput, error) {
	res := &svcsdk.CreateCachePolicyInput{}

	if r.ko.Spec.CachePolicyConfig != nil {
		f0 := &svcsdk.CachePolicyConfig{}
		if r.ko.Spec.CachePolicyConfig.Comment != nil {
			f0.SetComment(*r.ko.Spec.CachePolicyConfig.Comment)
		}
		if r.ko.Spec.CachePolicyConfig.DefaultTTL != nil {
			f0.SetDefaultTTL(*r.ko.Spec.CachePolicyConfig.DefaultTTL)
		}
		if r.ko.Spec.CachePolicyConfig.MaxTTL != nil {
			f0.SetMaxTTL(*r.ko.Spec.CachePolicyConfig.MaxTTL)
		}
		if r.ko.Spec.CachePolicyConfig.MinTTL != nil {
			f0.SetMinTTL(*r.ko.Spec.CachePolicyConfig.MinTTL)
		}
		if r.ko.Spec.CachePolicyConfig.Name != nil {
			f0.SetName(*r.ko.Spec.CachePolicyConfig.Name)
		}
		if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin != nil {
			f0f5 := &svcsdk.ParametersInCacheKeyAndForwardedToOrigin{}
			if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig != nil {
				f0f5f0 := &svcsdk.CachePolicyCookiesConfig{}
				if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.CookieBehavior != nil {
					f0f5f0.SetCookieBehavior(*r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.CookieBehavior)
				}
				if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.Cookies != nil {
					f0f5f0f1 := &svcsdk.CookieNames{}
					if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.Cookies.Items != nil {
						f0f5f0f1f0 := []*string{}
						for _, f0f5f0f1f0iter := range r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.Cookies.Items {
							var f0f5f0f1f0elem string
							f0f5f0f1f0elem = *f0f5f0f1f0iter
							f0f5f0f1f0 = append(f0f5f0f1f0, &f0f5f0f1f0elem)
						}
						f0f5f0f1.SetItems(f0f5f0f1f0)
					}
					f0f5f0.SetCookies(f0f5f0f1)
				}
				f0f5.SetCookiesConfig(f0f5f0)
			}
			if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingBrotli != nil {
				f0f5.SetEnableAcceptEncodingBrotli(*r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingBrotli)
			}
			if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingGzip != nil {
				f0f5.SetEnableAcceptEncodingGzip(*r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingGzip)
			}
			if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig != nil {
				f0f5f3 := &svcsdk.CachePolicyHeadersConfig{}
				if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.HeaderBehavior != nil {
					f0f5f3.SetHeaderBehavior(*r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.HeaderBehavior)
				}
				if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.Headers != nil {
					f0f5f3f1 := &svcsdk.Headers{}
					if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.Headers.Items != nil {
						f0f5f3f1f0 := []*string{}
						for _, f0f5f3f1f0iter := range r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.Headers.Items {
							var f0f5f3f1f0elem string
							f0f5f3f1f0elem = *f0f5f3f1f0iter
							f0f5f3f1f0 = append(f0f5f3f1f0, &f0f5f3f1f0elem)
						}
						f0f5f3f1.SetItems(f0f5f3f1f0)
					}
					f0f5f3.SetHeaders(f0f5f3f1)
				}
				f0f5.SetHeadersConfig(f0f5f3)
			}
			if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig != nil {
				f0f5f4 := &svcsdk.CachePolicyQueryStringsConfig{}
				if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStringBehavior != nil {
					f0f5f4.SetQueryStringBehavior(*r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStringBehavior)
				}
				if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStrings != nil {
					f0f5f4f1 := &svcsdk.QueryStringNames{}
					if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStrings.Items != nil {
						f0f5f4f1f0 := []*string{}
						for _, f0f5f4f1f0iter := range r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStrings.Items {
							var f0f5f4f1f0elem string
							f0f5f4f1f0elem = *f0f5f4f1f0iter
							f0f5f4f1f0 = append(f0f5f4f1f0, &f0f5f4f1f0elem)
						}
						f0f5f4f1.SetItems(f0f5f4f1f0)
					}
					f0f5f4.SetQueryStrings(f0f5f4f1)
				}
				f0f5.SetQueryStringsConfig(f0f5f4)
			}
			f0.SetParametersInCacheKeyAndForwardedToOrigin(f0f5)
		}
		res.SetCachePolicyConfig(f0)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}
	// If we don't do this, we get the following on every update call:
	// InvalidIfMatchVersion: The If-Match version is missing or not valid for the resource.
	if latest.ko.Status.ETag != nil {
		input.SetIfMatch(*latest.ko.Status.ETag)
	}
	// ¯\\\_(ツ)_/¯
	setQuantityFields(input.CachePolicyConfig)

	var resp *svcsdk.UpdateCachePolicyOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateCachePolicyWithContext(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateCachePolicy", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.ETag != nil {
		ko.Status.ETag = resp.ETag
	} else {
		ko.Status.ETag = nil
	}

	rm.setStatusDefaults(ko)
	// We need to do this manually because the ETag field (required for the
	// IfMatch field when updating or deleting a resource in CloudFront) is
	// outside the wrapper field of `CachePolicy` in the response and therefore
	// not picked up by SetResource code generation.
	if resp.ETag != nil {
		ko.Status.ETag = resp.ETag
	}

	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateCachePolicyInput, error) {
	res := &svcsdk.UpdateCachePolicyInput{}

	if r.ko.Spec.CachePolicyConfig != nil {
		f0 := &svcsdk.CachePolicyConfig{}
		if r.ko.Spec.CachePolicyConfig.Comment != nil {
			f0.SetComment(*r.ko.Spec.CachePolicyConfig.Comment)
		}
		if r.ko.Spec.CachePolicyConfig.DefaultTTL != nil {
			f0.SetDefaultTTL(*r.ko.Spec.CachePolicyConfig.DefaultTTL)
		}
		if r.ko.Spec.CachePolicyConfig.MaxTTL != nil {
			f0.SetMaxTTL(*r.ko.Spec.CachePolicyConfig.MaxTTL)
		}
		if r.ko.Spec.CachePolicyConfig.MinTTL != nil {
			f0.SetMinTTL(*r.ko.Spec.CachePolicyConfig.MinTTL)
		}
		if r.ko.Spec.CachePolicyConfig.Name != nil {
			f0.SetName(*r.ko.Spec.CachePolicyConfig.Name)
		}
		if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin != nil {
			f0f5 := &svcsdk.ParametersInCacheKeyAndForwardedToOrigin{}
			if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig != nil {
				f0f5f0 := &svcsdk.CachePolicyCookiesConfig{}
				if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.CookieBehavior != nil {
					f0f5f0.SetCookieBehavior(*r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.CookieBehavior)
				}
				if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.Cookies != nil {
					f0f5f0f1 := &svcsdk.CookieNames{}
					if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.Cookies.Items != nil {
						f0f5f0f1f0 := []*string{}
						for _, f0f5f0f1f0iter := range r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.Cookies.Items {
							var f0f5f0f1f0elem string
							f0f5f0f1f0elem = *f0f5f0f1f0iter
							f0f5f0f1f0 = append(f0f5f0f1f0, &f0f5f0f1f0elem)
						}
						f0f5f0f1.SetItems(f0f5f0f1f0)
					}
					f0f5f0.SetCookies(f0f5f0f1)
				}
				f0f5.SetCookiesConfig(f0f5f0)
			}
			if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingBrotli != nil {
				f0f5.SetEnableAcceptEncodingBrotli(*r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingBrotli)
			}
			if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingGzip != nil {
				f0f5.SetEnableAcceptEncodingGzip(*r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingGzip)
			}
			if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig != nil {
				f0f5f3 := &svcsdk.CachePolicyHeadersConfig{}
				if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.HeaderBehavior != nil {
					f0f5f3.SetHeaderBehavior(*r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.HeaderBehavior)
				}
				if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.Headers != nil {
					f0f5f3f1 := &svcsdk.Headers{}
					if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.Headers.Items != nil {
						f0f5f3f1f0 := []*string{}
						for _, f0f5f3f1f0iter := range r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.Headers.Items {
							var f0f5f3f1f0elem string
							f0f5f3f1f0elem = *f0f5f3f1f0iter
							f0f5f3f1f0 = append(f0f5f3f1f0, &f0f5f3f1f0elem)
						}
						f0f5f3f1.SetItems(f0f5f3f1f0)
					}
					f0f5f3.SetHeaders(f0f5f3f1)
				}
				f0f5.SetHeadersConfig(f0f5f3)
			}
			if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig != nil {
				f0f5f4 := &svcsdk.CachePolicyQueryStringsConfig{}
				if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStringBehavior != nil {
					f0f5f4.SetQueryStringBehavior(*r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStringBehavior)
				}
				if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStrings != nil {
					f0f5f4f1 := &svcsdk.QueryStringNames{}
					if r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStrings.Items != nil {
						f0f5f4f1f0 := []*string{}
						for _, f0f5f4f1f0iter := range r.ko.Spec.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.QueryStrings.Items {
							var f0f5f4f1f0elem string
							f0f5f4f1f0elem = *f0f5f4f1f0iter
							f0f5f4f1f0 = append(f0f5f4f1f0, &f0f5f4f1f0elem)
						}
						f0f5f4f1.SetItems(f0f5f4f1f0)
					}
					f0f5f4.SetQueryStrings(f0f5f4f1)
				}
				f0f5.SetQueryStringsConfig(f0f5f4)
			}
			f0.SetParametersInCacheKeyAndForwardedToOrigin(f0f5)
		}
		res.SetCachePolicyConfig(f0)
	}
	if r.ko.Status.ID != nil {
		res.SetId(*r.ko.Status.ID)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	// If we don't do this, we get the following on every delete call:
	// InvalidIfMatchVersion: The If-Match version is missing or not valid for the resource.
	if r.ko.Status.ETag != nil {
		input.SetIfMatch(*r.ko.Status.ETag)
	}

	var resp *svcsdk.DeleteCachePolicyOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteCachePolicyWithContext(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteCachePolicy", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteCachePolicyInput, error) {
	res := &svcsdk.DeleteCachePolicyInput{}

	if r.ko.Status.ID != nil {
		res.SetId(*r.ko.Status.ID)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.CachePolicy,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}
	awsErr, ok := ackerr.AWSError(err)
	if !ok {
		return false
	}
	switch awsErr.Code() {
	case "IllegalUpdate",
		"InconsistentQuantities",
		"InvalidArgument",
		"InvalidIfMatchVersion",
		"PreconditionFailed",
		"TooManyCookiesInCachePolicy",
		"TooManyHeadersInCachePolicy",
		"TooManyQueryStringsInCachePolicy":
		return true
	default:
		return false
	}
}
