// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DistributionTenantSpec defines the desired state of DistributionTenant.
//
// The distribution tenant.
type DistributionTenantSpec struct {

	// The ID of the connection group to associate with the distribution tenant.
	ConnectionGroupID  *string                                  `json:"connectionGroupID,omitempty"`
	ConnectionGroupRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"connectionGroupRef,omitempty"`
	// Customizations for the distribution tenant. For each distribution tenant,
	// you can specify the geographic restrictions, and the Amazon Resource Names
	// (ARNs) for the ACM certificate and WAF web ACL. These are specific values
	// that you can override or disable from the multi-tenant distribution that
	// was used to create the distribution tenant.
	Customizations *Customizations `json:"customizations,omitempty"`
	// The ID of the multi-tenant distribution to use for creating the distribution
	// tenant.
	DistributionID  *string                                  `json:"distributionID,omitempty"`
	DistributionRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"distributionRef,omitempty"`
	// The domains associated with the distribution tenant. You must specify at
	// least one domain in the request.
	// +kubebuilder:validation:Required
	Domains []*DomainItem `json:"domains"`
	// Indicates whether the distribution tenant should be enabled when created.
	// If the distribution tenant is disabled, the distribution tenant won't serve
	// traffic.
	Enabled *bool `json:"enabled,omitempty"`
	// The configuration for the CloudFront managed ACM certificate request.
	ManagedCertificateRequest *ManagedCertificateRequest `json:"managedCertificateRequest,omitempty"`
	// The name of the distribution tenant. Enter a friendly identifier that is
	// unique within your Amazon Web Services account. This name can't be updated
	// after you create the distribution tenant.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// A list of parameter values to add to the resource. A parameter is specified
	// as a key-value pair. A valid parameter value must exist for any parameter
	// that is marked as required in the multi-tenant distribution.
	Parameters []*Parameter `json:"parameters,omitempty"`
	// A complex type that contains Tag elements.
	Tags []*Tag `json:"tags,omitempty"`
}

// DistributionTenantStatus defines the observed state of DistributionTenant
type DistributionTenantStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The date and time when the distribution tenant was created.
	// +kubebuilder:validation:Optional
	CreatedTime *metav1.Time `json:"createdTime,omitempty"`
	// +kubebuilder:validation:Optional
	ETag *string `json:"eTag,omitempty"`
	// The ID of the distribution tenant.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
	// The date and time when the distribution tenant was updated.
	// +kubebuilder:validation:Optional
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
	// The status of the distribution tenant.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
}

// DistributionTenant is the Schema for the DistributionTenants API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type DistributionTenant struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DistributionTenantSpec   `json:"spec,omitempty"`
	Status            DistributionTenantStatus `json:"status,omitempty"`
}

// DistributionTenantList contains a list of DistributionTenant
// +kubebuilder:object:root=true
type DistributionTenantList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DistributionTenant `json:"items"`
}

func init() {
	SchemeBuilder.Register(&DistributionTenant{}, &DistributionTenantList{})
}
