// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DistributionSpec defines the desired state of Distribution.
//
// A distribution tells CloudFront where you want content to be delivered from,
// and the details about how to track and manage content delivery.
type DistributionSpec struct {

	// The distribution's configuration information.
	// +kubebuilder:validation:Required
	DistributionConfig *DistributionConfig `json:"distributionConfig"`
}

// DistributionStatus defines the observed state of Distribution
type DistributionStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// This field contains a list of key groups and the public keys in each key
	// group that CloudFront can use to verify the signatures of signed URLs or
	// signed cookies.
	// +kubebuilder:validation:Optional
	ActiveTrustedKeyGroups *ActiveTrustedKeyGroups `json:"activeTrustedKeyGroups,omitempty"`
	//
	// We recommend using TrustedKeyGroups instead of TrustedSigners.
	//
	// This field contains a list of Amazon Web Services account IDs and the active
	// CloudFront key pairs in each account that CloudFront can use to verify the
	// signatures of signed URLs or signed cookies.
	// +kubebuilder:validation:Optional
	ActiveTrustedSigners *ActiveTrustedSigners `json:"activeTrustedSigners,omitempty"`
	// Amazon Web Services services in China customers must file for an Internet
	// Content Provider (ICP) recordal if they want to serve content publicly on
	// an alternate domain name, also known as a CNAME, that they've added to CloudFront.
	// AliasICPRecordal provides the ICP recordal status for CNAMEs associated with
	// distributions.
	//
	// For more information about ICP recordals, see Signup, Accounts, and Credentials
	// (https://docs.amazonaws.cn/en_us/aws/latest/userguide/accounts-and-credentials.html)
	// in Getting Started with Amazon Web Services services in China.
	// +kubebuilder:validation:Optional
	AliasICPRecordals []*AliasICPRecordal `json:"aliasICPRecordals,omitempty"`
	// +kubebuilder:validation:Optional
	CallerReference *string `json:"callerReference,omitempty"`
	// The distribution's CloudFront domain name. For example: d111111abcdef8.cloudfront.net.
	// +kubebuilder:validation:Optional
	DomainName *string `json:"domainName,omitempty"`
	// The current version of the distribution created.
	// +kubebuilder:validation:Optional
	ETag *string `json:"eTag,omitempty"`
	// The distribution's identifier. For example: E1U5RQF7T870K0.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
	// The number of invalidation batches currently in progress.
	// +kubebuilder:validation:Optional
	InProgressInvalidationBatches *int64 `json:"inProgressInvalidationBatches,omitempty"`
	// The date and time when the distribution was last modified.
	// +kubebuilder:validation:Optional
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
	// The distribution's status. When the status is Deployed, the distribution's
	// information is fully propagated to all CloudFront edge locations.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
}

// Distribution is the Schema for the Distributions API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type Distribution struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DistributionSpec   `json:"spec,omitempty"`
	Status            DistributionStatus `json:"status,omitempty"`
}

// DistributionList contains a list of Distribution
// +kubebuilder:object:root=true
type DistributionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Distribution `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Distribution{}, &DistributionList{})
}
