// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type CachePolicyCookieBehavior string

const (
	CachePolicyCookieBehavior_all       CachePolicyCookieBehavior = "all"
	CachePolicyCookieBehavior_allExcept CachePolicyCookieBehavior = "allExcept"
	CachePolicyCookieBehavior_none      CachePolicyCookieBehavior = "none"
	CachePolicyCookieBehavior_whitelist CachePolicyCookieBehavior = "whitelist"
)

type CachePolicyHeaderBehavior string

const (
	CachePolicyHeaderBehavior_none      CachePolicyHeaderBehavior = "none"
	CachePolicyHeaderBehavior_whitelist CachePolicyHeaderBehavior = "whitelist"
)

type CachePolicyQueryStringBehavior string

const (
	CachePolicyQueryStringBehavior_all       CachePolicyQueryStringBehavior = "all"
	CachePolicyQueryStringBehavior_allExcept CachePolicyQueryStringBehavior = "allExcept"
	CachePolicyQueryStringBehavior_none      CachePolicyQueryStringBehavior = "none"
	CachePolicyQueryStringBehavior_whitelist CachePolicyQueryStringBehavior = "whitelist"
)

type CachePolicyType string

const (
	CachePolicyType_custom  CachePolicyType = "custom"
	CachePolicyType_managed CachePolicyType = "managed"
)

type CertificateSource string

const (
	CertificateSource_acm        CertificateSource = "acm"
	CertificateSource_cloudfront CertificateSource = "cloudfront"
	CertificateSource_iam        CertificateSource = "iam"
)

type CertificateTransparencyLoggingPreference string

const (
	CertificateTransparencyLoggingPreference_disabled CertificateTransparencyLoggingPreference = "disabled"
	CertificateTransparencyLoggingPreference_enabled  CertificateTransparencyLoggingPreference = "enabled"
)

type ConnectionMode string

const (
	ConnectionMode_direct      ConnectionMode = "direct"
	ConnectionMode_tenant_only ConnectionMode = "tenant-only"
)

type ContinuousDeploymentPolicyType string

const (
	ContinuousDeploymentPolicyType_SingleHeader ContinuousDeploymentPolicyType = "SingleHeader"
	ContinuousDeploymentPolicyType_SingleWeight ContinuousDeploymentPolicyType = "SingleWeight"
)

type CustomizationActionType string

const (
	CustomizationActionType_disable  CustomizationActionType = "disable"
	CustomizationActionType_override CustomizationActionType = "override"
)

type DNSConfigurationStatus string

const (
	DNSConfigurationStatus_invalid_configuration DNSConfigurationStatus = "invalid-configuration"
	DNSConfigurationStatus_unknown_configuration DNSConfigurationStatus = "unknown-configuration"
	DNSConfigurationStatus_valid_configuration   DNSConfigurationStatus = "valid-configuration"
)

type DistributionResourceType string

const (
	DistributionResourceType_distribution        DistributionResourceType = "distribution"
	DistributionResourceType_distribution_tenant DistributionResourceType = "distribution-tenant"
)

type DomainStatus string

const (
	DomainStatus_active   DomainStatus = "active"
	DomainStatus_inactive DomainStatus = "inactive"
)

type EventType string

const (
	EventType_origin_request  EventType = "origin-request"
	EventType_origin_response EventType = "origin-response"
	EventType_viewer_request  EventType = "viewer-request"
	EventType_viewer_response EventType = "viewer-response"
)

type Format string

const (
	Format_URLEncoded Format = "URLEncoded"
)

type FrameOptionsList string

const (
	FrameOptionsList_DENY       FrameOptionsList = "DENY"
	FrameOptionsList_SAMEORIGIN FrameOptionsList = "SAMEORIGIN"
)

type FunctionRuntime string

const (
	FunctionRuntime_cloudfront_js_1_0 FunctionRuntime = "cloudfront-js-1.0"
	FunctionRuntime_cloudfront_js_2_0 FunctionRuntime = "cloudfront-js-2.0"
)

type FunctionStage string

const (
	FunctionStage_DEVELOPMENT FunctionStage = "DEVELOPMENT"
	FunctionStage_LIVE        FunctionStage = "LIVE"
)

type GeoRestrictionType string

const (
	GeoRestrictionType_blacklist GeoRestrictionType = "blacklist"
	GeoRestrictionType_none      GeoRestrictionType = "none"
	GeoRestrictionType_whitelist GeoRestrictionType = "whitelist"
)

type HTTPVersion string

const (
	HTTPVersion_http1_1   HTTPVersion = "http1.1"
	HTTPVersion_http2     HTTPVersion = "http2"
	HTTPVersion_http2and3 HTTPVersion = "http2and3"
	HTTPVersion_http3     HTTPVersion = "http3"
)

type ICPRecordalStatus string

const (
	ICPRecordalStatus_APPROVED  ICPRecordalStatus = "APPROVED"
	ICPRecordalStatus_PENDING   ICPRecordalStatus = "PENDING"
	ICPRecordalStatus_SUSPENDED ICPRecordalStatus = "SUSPENDED"
)

type IPAMCIDRStatus string

const (
	IPAMCIDRStatus_advertised         IPAMCIDRStatus = "advertised"
	IPAMCIDRStatus_advertising        IPAMCIDRStatus = "advertising"
	IPAMCIDRStatus_deprovisioned      IPAMCIDRStatus = "deprovisioned"
	IPAMCIDRStatus_deprovisioning     IPAMCIDRStatus = "deprovisioning"
	IPAMCIDRStatus_failed_advertise   IPAMCIDRStatus = "failed-advertise"
	IPAMCIDRStatus_failed_deprovision IPAMCIDRStatus = "failed-deprovision"
	IPAMCIDRStatus_failed_provision   IPAMCIDRStatus = "failed-provision"
	IPAMCIDRStatus_failed_withdraw    IPAMCIDRStatus = "failed-withdraw"
	IPAMCIDRStatus_provisioned        IPAMCIDRStatus = "provisioned"
	IPAMCIDRStatus_provisioning       IPAMCIDRStatus = "provisioning"
	IPAMCIDRStatus_withdrawing        IPAMCIDRStatus = "withdrawing"
	IPAMCIDRStatus_withdrawn          IPAMCIDRStatus = "withdrawn"
)

type IPAddressType string

const (
	IPAddressType_dualstack IPAddressType = "dualstack"
	IPAddressType_ipv4      IPAddressType = "ipv4"
	IPAddressType_ipv6      IPAddressType = "ipv6"
)

type ImportSourceType string

const (
	ImportSourceType_S3 ImportSourceType = "S3"
)

type ItemSelection string

const (
	ItemSelection_all       ItemSelection = "all"
	ItemSelection_none      ItemSelection = "none"
	ItemSelection_whitelist ItemSelection = "whitelist"
)

type ManagedCertificateStatus string

const (
	ManagedCertificateStatus_expired              ManagedCertificateStatus = "expired"
	ManagedCertificateStatus_failed               ManagedCertificateStatus = "failed"
	ManagedCertificateStatus_inactive             ManagedCertificateStatus = "inactive"
	ManagedCertificateStatus_issued               ManagedCertificateStatus = "issued"
	ManagedCertificateStatus_pending_validation   ManagedCertificateStatus = "pending-validation"
	ManagedCertificateStatus_revoked              ManagedCertificateStatus = "revoked"
	ManagedCertificateStatus_validation_timed_out ManagedCertificateStatus = "validation-timed-out"
)

type Method string

const (
	Method_DELETE  Method = "DELETE"
	Method_GET     Method = "GET"
	Method_HEAD    Method = "HEAD"
	Method_OPTIONS Method = "OPTIONS"
	Method_PATCH   Method = "PATCH"
	Method_POST    Method = "POST"
	Method_PUT     Method = "PUT"
)

type MinimumProtocolVersion string

const (
	MinimumProtocolVersion_SSLv3        MinimumProtocolVersion = "SSLv3"
	MinimumProtocolVersion_TLSv1        MinimumProtocolVersion = "TLSv1"
	MinimumProtocolVersion_TLSv1_1_2016 MinimumProtocolVersion = "TLSv1.1_2016"
	MinimumProtocolVersion_TLSv1_2_2018 MinimumProtocolVersion = "TLSv1.2_2018"
	MinimumProtocolVersion_TLSv1_2_2019 MinimumProtocolVersion = "TLSv1.2_2019"
	MinimumProtocolVersion_TLSv1_2_2021 MinimumProtocolVersion = "TLSv1.2_2021"
	MinimumProtocolVersion_TLSv1_2_2025 MinimumProtocolVersion = "TLSv1.2_2025"
	MinimumProtocolVersion_TLSv1_3_2025 MinimumProtocolVersion = "TLSv1.3_2025"
	MinimumProtocolVersion_TLSv1_2016   MinimumProtocolVersion = "TLSv1_2016"
)

type OriginAccessControlOriginTypes string

const (
	OriginAccessControlOriginTypes_lambda         OriginAccessControlOriginTypes = "lambda"
	OriginAccessControlOriginTypes_mediapackagev2 OriginAccessControlOriginTypes = "mediapackagev2"
	OriginAccessControlOriginTypes_mediastore     OriginAccessControlOriginTypes = "mediastore"
	OriginAccessControlOriginTypes_s3             OriginAccessControlOriginTypes = "s3"
)

type OriginAccessControlSigningBehaviors string

const (
	OriginAccessControlSigningBehaviors_always      OriginAccessControlSigningBehaviors = "always"
	OriginAccessControlSigningBehaviors_never       OriginAccessControlSigningBehaviors = "never"
	OriginAccessControlSigningBehaviors_no_override OriginAccessControlSigningBehaviors = "no-override"
)

type OriginAccessControlSigningProtocols string

const (
	OriginAccessControlSigningProtocols_sigv4 OriginAccessControlSigningProtocols = "sigv4"
)

type OriginGroupSelectionCriteria string

const (
	OriginGroupSelectionCriteria_default             OriginGroupSelectionCriteria = "default"
	OriginGroupSelectionCriteria_media_quality_based OriginGroupSelectionCriteria = "media-quality-based"
)

type OriginProtocolPolicy string

const (
	OriginProtocolPolicy_http_only    OriginProtocolPolicy = "http-only"
	OriginProtocolPolicy_https_only   OriginProtocolPolicy = "https-only"
	OriginProtocolPolicy_match_viewer OriginProtocolPolicy = "match-viewer"
)

type OriginRequestPolicyCookieBehavior string

const (
	OriginRequestPolicyCookieBehavior_all       OriginRequestPolicyCookieBehavior = "all"
	OriginRequestPolicyCookieBehavior_allExcept OriginRequestPolicyCookieBehavior = "allExcept"
	OriginRequestPolicyCookieBehavior_none      OriginRequestPolicyCookieBehavior = "none"
	OriginRequestPolicyCookieBehavior_whitelist OriginRequestPolicyCookieBehavior = "whitelist"
)

type OriginRequestPolicyHeaderBehavior string

const (
	OriginRequestPolicyHeaderBehavior_allExcept                       OriginRequestPolicyHeaderBehavior = "allExcept"
	OriginRequestPolicyHeaderBehavior_allViewer                       OriginRequestPolicyHeaderBehavior = "allViewer"
	OriginRequestPolicyHeaderBehavior_allViewerAndWhitelistCloudFront OriginRequestPolicyHeaderBehavior = "allViewerAndWhitelistCloudFront"
	OriginRequestPolicyHeaderBehavior_none                            OriginRequestPolicyHeaderBehavior = "none"
	OriginRequestPolicyHeaderBehavior_whitelist                       OriginRequestPolicyHeaderBehavior = "whitelist"
)

type OriginRequestPolicyQueryStringBehavior string

const (
	OriginRequestPolicyQueryStringBehavior_all       OriginRequestPolicyQueryStringBehavior = "all"
	OriginRequestPolicyQueryStringBehavior_allExcept OriginRequestPolicyQueryStringBehavior = "allExcept"
	OriginRequestPolicyQueryStringBehavior_none      OriginRequestPolicyQueryStringBehavior = "none"
	OriginRequestPolicyQueryStringBehavior_whitelist OriginRequestPolicyQueryStringBehavior = "whitelist"
)

type OriginRequestPolicyType string

const (
	OriginRequestPolicyType_custom  OriginRequestPolicyType = "custom"
	OriginRequestPolicyType_managed OriginRequestPolicyType = "managed"
)

type PriceClass string

const (
	PriceClass_None           PriceClass = "None"
	PriceClass_PriceClass_100 PriceClass = "PriceClass_100"
	PriceClass_PriceClass_200 PriceClass = "PriceClass_200"
	PriceClass_PriceClass_All PriceClass = "PriceClass_All"
)

type RealtimeMetricsSubscriptionStatus string

const (
	RealtimeMetricsSubscriptionStatus_Disabled RealtimeMetricsSubscriptionStatus = "Disabled"
	RealtimeMetricsSubscriptionStatus_Enabled  RealtimeMetricsSubscriptionStatus = "Enabled"
)

type ReferrerPolicyList string

const (
	ReferrerPolicyList_no_referrer                     ReferrerPolicyList = "no-referrer"
	ReferrerPolicyList_no_referrer_when_downgrade      ReferrerPolicyList = "no-referrer-when-downgrade"
	ReferrerPolicyList_origin                          ReferrerPolicyList = "origin"
	ReferrerPolicyList_origin_when_cross_origin        ReferrerPolicyList = "origin-when-cross-origin"
	ReferrerPolicyList_same_origin                     ReferrerPolicyList = "same-origin"
	ReferrerPolicyList_strict_origin                   ReferrerPolicyList = "strict-origin"
	ReferrerPolicyList_strict_origin_when_cross_origin ReferrerPolicyList = "strict-origin-when-cross-origin"
	ReferrerPolicyList_unsafe_url                      ReferrerPolicyList = "unsafe-url"
)

type ResponseHeadersPolicyAccessControlAllowMethodsValues string

const (
	ResponseHeadersPolicyAccessControlAllowMethodsValues_ALL     ResponseHeadersPolicyAccessControlAllowMethodsValues = "ALL"
	ResponseHeadersPolicyAccessControlAllowMethodsValues_DELETE  ResponseHeadersPolicyAccessControlAllowMethodsValues = "DELETE"
	ResponseHeadersPolicyAccessControlAllowMethodsValues_GET     ResponseHeadersPolicyAccessControlAllowMethodsValues = "GET"
	ResponseHeadersPolicyAccessControlAllowMethodsValues_HEAD    ResponseHeadersPolicyAccessControlAllowMethodsValues = "HEAD"
	ResponseHeadersPolicyAccessControlAllowMethodsValues_OPTIONS ResponseHeadersPolicyAccessControlAllowMethodsValues = "OPTIONS"
	ResponseHeadersPolicyAccessControlAllowMethodsValues_PATCH   ResponseHeadersPolicyAccessControlAllowMethodsValues = "PATCH"
	ResponseHeadersPolicyAccessControlAllowMethodsValues_POST    ResponseHeadersPolicyAccessControlAllowMethodsValues = "POST"
	ResponseHeadersPolicyAccessControlAllowMethodsValues_PUT     ResponseHeadersPolicyAccessControlAllowMethodsValues = "PUT"
)

type ResponseHeadersPolicyType string

const (
	ResponseHeadersPolicyType_custom  ResponseHeadersPolicyType = "custom"
	ResponseHeadersPolicyType_managed ResponseHeadersPolicyType = "managed"
)

type SSLProtocol string

const (
	SSLProtocol_SSLv3   SSLProtocol = "SSLv3"
	SSLProtocol_TLSv1   SSLProtocol = "TLSv1"
	SSLProtocol_TLSv1_1 SSLProtocol = "TLSv1.1"
	SSLProtocol_TLSv1_2 SSLProtocol = "TLSv1.2"
)

type SSLSupportMethod string

const (
	SSLSupportMethod_sni_only  SSLSupportMethod = "sni-only"
	SSLSupportMethod_static_ip SSLSupportMethod = "static-ip"
	SSLSupportMethod_vip       SSLSupportMethod = "vip"
)

type TrustStoreStatus string

const (
	TrustStoreStatus_active  TrustStoreStatus = "active"
	TrustStoreStatus_failed  TrustStoreStatus = "failed"
	TrustStoreStatus_pending TrustStoreStatus = "pending"
)

type ValidationTokenHost string

const (
	ValidationTokenHost_cloudfront  ValidationTokenHost = "cloudfront"
	ValidationTokenHost_self_hosted ValidationTokenHost = "self-hosted"
)

type ViewerMtlsMode string

const (
	ViewerMtlsMode_optional ViewerMtlsMode = "optional"
	ViewerMtlsMode_required ViewerMtlsMode = "required"
)

type ViewerProtocolPolicy string

const (
	ViewerProtocolPolicy_allow_all         ViewerProtocolPolicy = "allow-all"
	ViewerProtocolPolicy_https_only        ViewerProtocolPolicy = "https-only"
	ViewerProtocolPolicy_redirect_to_https ViewerProtocolPolicy = "redirect-to-https"
)
