// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// FunctionSpec defines the desired state of Function.
type FunctionSpec struct {

	// The function code. For more information about writing a CloudFront function,
	// see Writing function code for CloudFront Functions (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/writing-function-code.html)
	// in the Amazon CloudFront Developer Guide.
	// +kubebuilder:validation:Required
	FunctionCode []byte `json:"functionCode"`
	// Configuration information about the function, including an optional comment
	// and the function's runtime.
	// +kubebuilder:validation:Required
	FunctionConfig *FunctionConfig `json:"functionConfig"`
	// A name to identify the function.
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
}

// FunctionStatus defines the observed state of Function
type FunctionStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The version identifier for the current version of the CloudFront function.
	// +kubebuilder:validation:Optional
	ETag *string `json:"eTag,omitempty"`
	// Contains configuration information and metadata about a CloudFront function.
	// +kubebuilder:validation:Optional
	FunctionSummary *FunctionSummary `json:"functionSummary,omitempty"`
	// The URL of the CloudFront function. Use the URL to manage the function with
	// the CloudFront API.
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty"`
}

// Function is the Schema for the Functions API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type Function struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              FunctionSpec   `json:"spec,omitempty"`
	Status            FunctionStatus `json:"status,omitempty"`
}

// FunctionList contains a list of Function
// +kubebuilder:object:root=true
type FunctionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Function `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Function{}, &FunctionList{})
}
