// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// OriginRequestPolicySpec defines the desired state of OriginRequestPolicy.
//
// An origin request policy.
//
// When it's attached to a cache behavior, the origin request policy determines
// the values that CloudFront includes in requests that it sends to the origin.
// Each request that CloudFront sends to the origin includes the following:
//
//   - The request body and the URL path (without the domain name) from the
//     viewer request.
//
//   - The headers that CloudFront automatically includes in every origin request,
//     including Host, User-Agent, and X-Amz-Cf-Id.
//
//   - All HTTP headers, cookies, and URL query strings that are specified
//     in the cache policy or the origin request policy. These can include items
//     from the viewer request and, in the case of headers, additional ones that
//     are added by CloudFront.
//
// CloudFront sends a request when it can't find an object in its cache that
// matches the request. If you want to send values to the origin and also include
// them in the cache key, use CachePolicy.
type OriginRequestPolicySpec struct {

	// An origin request policy configuration.
	// +kubebuilder:validation:Required
	OriginRequestPolicyConfig *OriginRequestPolicyConfig `json:"originRequestPolicyConfig"`
}

// OriginRequestPolicyStatus defines the observed state of OriginRequestPolicy
type OriginRequestPolicyStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// +kubebuilder:validation:Optional
	ETag *string `json:"eTag,omitempty"`
	// The unique identifier for the origin request policy.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
	// The date and time when the origin request policy was last modified.
	// +kubebuilder:validation:Optional
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty"`
}

// OriginRequestPolicy is the Schema for the OriginRequestPolicies API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type OriginRequestPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              OriginRequestPolicySpec   `json:"spec,omitempty"`
	Status            OriginRequestPolicyStatus `json:"status,omitempty"`
}

// OriginRequestPolicyList contains a list of OriginRequestPolicy
// +kubebuilder:object:root=true
type OriginRequestPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OriginRequestPolicy `json:"items"`
}

func init() {
	SchemeBuilder.Register(&OriginRequestPolicy{}, &OriginRequestPolicyList{})
}
