// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VpcOriginSpec defines the desired state of VpcOrigin.
//
// An Amazon CloudFront VPC origin.
type VPCOriginSpec struct {
	Tags *Tags `json:"tags,omitempty"`
	// The VPC origin endpoint configuration.
	// +kubebuilder:validation:Required
	VPCOriginEndpointConfig *VPCOriginEndpointConfig `json:"vpcOriginEndpointConfig"`
}

// VPCOriginStatus defines the observed state of VPCOrigin
type VPCOriginStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The VPC origin created time.
	// +kubebuilder:validation:Optional
	CreatedTime *metav1.Time `json:"createdTime,omitempty"`
	// The VPC origin ID.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
	// The VPC origin last modified time.
	// +kubebuilder:validation:Optional
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
	// The VPC origin status.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
}

// VPCOrigin is the Schema for the VPCOrigins API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type VPCOrigin struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              VPCOriginSpec   `json:"spec,omitempty"`
	Status            VPCOriginStatus `json:"status,omitempty"`
}

// VPCOriginList contains a list of VPCOrigin
// +kubebuilder:object:root=true
type VPCOriginList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VPCOrigin `json:"items"`
}

func init() {
	SchemeBuilder.Register(&VPCOrigin{}, &VPCOriginList{})
}
