// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package origin_request_policy

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/cloudfront"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/cloudfront-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.CloudFront{}
	_ = &svcapitypes.OriginRequestPolicy{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetOriginRequestPolicyOutput
	resp, err = rm.sdkapi.GetOriginRequestPolicyWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetOriginRequestPolicy", err)
	if err != nil {
		if reqErr, ok := ackerr.AWSRequestFailure(err); ok && reqErr.StatusCode() == 404 {
			return nil, ackerr.NotFound
		}
		if awsErr, ok := ackerr.AWSError(err); ok && awsErr.Code() == "NoSuchOriginRequestPolicy" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.OriginRequestPolicy.Id != nil {
		ko.Status.ID = resp.OriginRequestPolicy.Id
	} else {
		ko.Status.ID = nil
	}
	if resp.OriginRequestPolicy.LastModifiedTime != nil {
		ko.Status.LastModifiedTime = &metav1.Time{*resp.OriginRequestPolicy.LastModifiedTime}
	} else {
		ko.Status.LastModifiedTime = nil
	}
	if resp.OriginRequestPolicy.OriginRequestPolicyConfig != nil {
		f2 := &svcapitypes.OriginRequestPolicyConfig{}
		if resp.OriginRequestPolicy.OriginRequestPolicyConfig.Comment != nil {
			f2.Comment = resp.OriginRequestPolicy.OriginRequestPolicyConfig.Comment
		}
		if resp.OriginRequestPolicy.OriginRequestPolicyConfig.CookiesConfig != nil {
			f2f1 := &svcapitypes.OriginRequestPolicyCookiesConfig{}
			if resp.OriginRequestPolicy.OriginRequestPolicyConfig.CookiesConfig.CookieBehavior != nil {
				f2f1.CookieBehavior = resp.OriginRequestPolicy.OriginRequestPolicyConfig.CookiesConfig.CookieBehavior
			}
			if resp.OriginRequestPolicy.OriginRequestPolicyConfig.CookiesConfig.Cookies != nil {
				f2f1f1 := &svcapitypes.CookieNames{}
				if resp.OriginRequestPolicy.OriginRequestPolicyConfig.CookiesConfig.Cookies.Items != nil {
					f2f1f1f0 := []*string{}
					for _, f2f1f1f0iter := range resp.OriginRequestPolicy.OriginRequestPolicyConfig.CookiesConfig.Cookies.Items {
						var f2f1f1f0elem string
						f2f1f1f0elem = *f2f1f1f0iter
						f2f1f1f0 = append(f2f1f1f0, &f2f1f1f0elem)
					}
					f2f1f1.Items = f2f1f1f0
				}
				f2f1.Cookies = f2f1f1
			}
			f2.CookiesConfig = f2f1
		}
		if resp.OriginRequestPolicy.OriginRequestPolicyConfig.HeadersConfig != nil {
			f2f2 := &svcapitypes.OriginRequestPolicyHeadersConfig{}
			if resp.OriginRequestPolicy.OriginRequestPolicyConfig.HeadersConfig.HeaderBehavior != nil {
				f2f2.HeaderBehavior = resp.OriginRequestPolicy.OriginRequestPolicyConfig.HeadersConfig.HeaderBehavior
			}
			if resp.OriginRequestPolicy.OriginRequestPolicyConfig.HeadersConfig.Headers != nil {
				f2f2f1 := &svcapitypes.Headers{}
				if resp.OriginRequestPolicy.OriginRequestPolicyConfig.HeadersConfig.Headers.Items != nil {
					f2f2f1f0 := []*string{}
					for _, f2f2f1f0iter := range resp.OriginRequestPolicy.OriginRequestPolicyConfig.HeadersConfig.Headers.Items {
						var f2f2f1f0elem string
						f2f2f1f0elem = *f2f2f1f0iter
						f2f2f1f0 = append(f2f2f1f0, &f2f2f1f0elem)
					}
					f2f2f1.Items = f2f2f1f0
				}
				f2f2.Headers = f2f2f1
			}
			f2.HeadersConfig = f2f2
		}
		if resp.OriginRequestPolicy.OriginRequestPolicyConfig.Name != nil {
			f2.Name = resp.OriginRequestPolicy.OriginRequestPolicyConfig.Name
		}
		if resp.OriginRequestPolicy.OriginRequestPolicyConfig.QueryStringsConfig != nil {
			f2f4 := &svcapitypes.OriginRequestPolicyQueryStringsConfig{}
			if resp.OriginRequestPolicy.OriginRequestPolicyConfig.QueryStringsConfig.QueryStringBehavior != nil {
				f2f4.QueryStringBehavior = resp.OriginRequestPolicy.OriginRequestPolicyConfig.QueryStringsConfig.QueryStringBehavior
			}
			if resp.OriginRequestPolicy.OriginRequestPolicyConfig.QueryStringsConfig.QueryStrings != nil {
				f2f4f1 := &svcapitypes.QueryStringNames{}
				if resp.OriginRequestPolicy.OriginRequestPolicyConfig.QueryStringsConfig.QueryStrings.Items != nil {
					f2f4f1f0 := []*string{}
					for _, f2f4f1f0iter := range resp.OriginRequestPolicy.OriginRequestPolicyConfig.QueryStringsConfig.QueryStrings.Items {
						var f2f4f1f0elem string
						f2f4f1f0elem = *f2f4f1f0iter
						f2f4f1f0 = append(f2f4f1f0, &f2f4f1f0elem)
					}
					f2f4f1.Items = f2f4f1f0
				}
				f2f4.QueryStrings = f2f4f1
			}
			f2.QueryStringsConfig = f2f4
		}
		ko.Spec.OriginRequestPolicyConfig = f2
	} else {
		ko.Spec.OriginRequestPolicyConfig = nil
	}

	rm.setStatusDefaults(ko)
	// We need to do this manually because the ETag field (required for the
	// IfMatch field when updating or deleting a resource in CloudFront) is
	// outside the wrapper field of `OriginRequestPolicy` in the response
	// and therefore not picked up by SetResource code generation.
	if resp.ETag != nil {
		ko.Status.ETag = resp.ETag
	}
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.ID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetOriginRequestPolicyInput, error) {
	res := &svcsdk.GetOriginRequestPolicyInput{}

	if r.ko.Status.ID != nil {
		res.SetId(*r.ko.Status.ID)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}
	// ¯\\\_(ツ)_/¯
	setQuantityFields(input.OriginRequestPolicyConfig)

	var resp *svcsdk.CreateOriginRequestPolicyOutput
	_ = resp
	resp, err = rm.sdkapi.CreateOriginRequestPolicyWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateOriginRequestPolicy", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.OriginRequestPolicy.Id != nil {
		ko.Status.ID = resp.OriginRequestPolicy.Id
	} else {
		ko.Status.ID = nil
	}
	if resp.OriginRequestPolicy.LastModifiedTime != nil {
		ko.Status.LastModifiedTime = &metav1.Time{*resp.OriginRequestPolicy.LastModifiedTime}
	} else {
		ko.Status.LastModifiedTime = nil
	}
	if resp.OriginRequestPolicy.OriginRequestPolicyConfig != nil {
		f2 := &svcapitypes.OriginRequestPolicyConfig{}
		if resp.OriginRequestPolicy.OriginRequestPolicyConfig.Comment != nil {
			f2.Comment = resp.OriginRequestPolicy.OriginRequestPolicyConfig.Comment
		}
		if resp.OriginRequestPolicy.OriginRequestPolicyConfig.CookiesConfig != nil {
			f2f1 := &svcapitypes.OriginRequestPolicyCookiesConfig{}
			if resp.OriginRequestPolicy.OriginRequestPolicyConfig.CookiesConfig.CookieBehavior != nil {
				f2f1.CookieBehavior = resp.OriginRequestPolicy.OriginRequestPolicyConfig.CookiesConfig.CookieBehavior
			}
			if resp.OriginRequestPolicy.OriginRequestPolicyConfig.CookiesConfig.Cookies != nil {
				f2f1f1 := &svcapitypes.CookieNames{}
				if resp.OriginRequestPolicy.OriginRequestPolicyConfig.CookiesConfig.Cookies.Items != nil {
					f2f1f1f0 := []*string{}
					for _, f2f1f1f0iter := range resp.OriginRequestPolicy.OriginRequestPolicyConfig.CookiesConfig.Cookies.Items {
						var f2f1f1f0elem string
						f2f1f1f0elem = *f2f1f1f0iter
						f2f1f1f0 = append(f2f1f1f0, &f2f1f1f0elem)
					}
					f2f1f1.Items = f2f1f1f0
				}
				f2f1.Cookies = f2f1f1
			}
			f2.CookiesConfig = f2f1
		}
		if resp.OriginRequestPolicy.OriginRequestPolicyConfig.HeadersConfig != nil {
			f2f2 := &svcapitypes.OriginRequestPolicyHeadersConfig{}
			if resp.OriginRequestPolicy.OriginRequestPolicyConfig.HeadersConfig.HeaderBehavior != nil {
				f2f2.HeaderBehavior = resp.OriginRequestPolicy.OriginRequestPolicyConfig.HeadersConfig.HeaderBehavior
			}
			if resp.OriginRequestPolicy.OriginRequestPolicyConfig.HeadersConfig.Headers != nil {
				f2f2f1 := &svcapitypes.Headers{}
				if resp.OriginRequestPolicy.OriginRequestPolicyConfig.HeadersConfig.Headers.Items != nil {
					f2f2f1f0 := []*string{}
					for _, f2f2f1f0iter := range resp.OriginRequestPolicy.OriginRequestPolicyConfig.HeadersConfig.Headers.Items {
						var f2f2f1f0elem string
						f2f2f1f0elem = *f2f2f1f0iter
						f2f2f1f0 = append(f2f2f1f0, &f2f2f1f0elem)
					}
					f2f2f1.Items = f2f2f1f0
				}
				f2f2.Headers = f2f2f1
			}
			f2.HeadersConfig = f2f2
		}
		if resp.OriginRequestPolicy.OriginRequestPolicyConfig.Name != nil {
			f2.Name = resp.OriginRequestPolicy.OriginRequestPolicyConfig.Name
		}
		if resp.OriginRequestPolicy.OriginRequestPolicyConfig.QueryStringsConfig != nil {
			f2f4 := &svcapitypes.OriginRequestPolicyQueryStringsConfig{}
			if resp.OriginRequestPolicy.OriginRequestPolicyConfig.QueryStringsConfig.QueryStringBehavior != nil {
				f2f4.QueryStringBehavior = resp.OriginRequestPolicy.OriginRequestPolicyConfig.QueryStringsConfig.QueryStringBehavior
			}
			if resp.OriginRequestPolicy.OriginRequestPolicyConfig.QueryStringsConfig.QueryStrings != nil {
				f2f4f1 := &svcapitypes.QueryStringNames{}
				if resp.OriginRequestPolicy.OriginRequestPolicyConfig.QueryStringsConfig.QueryStrings.Items != nil {
					f2f4f1f0 := []*string{}
					for _, f2f4f1f0iter := range resp.OriginRequestPolicy.OriginRequestPolicyConfig.QueryStringsConfig.QueryStrings.Items {
						var f2f4f1f0elem string
						f2f4f1f0elem = *f2f4f1f0iter
						f2f4f1f0 = append(f2f4f1f0, &f2f4f1f0elem)
					}
					f2f4f1.Items = f2f4f1f0
				}
				f2f4.QueryStrings = f2f4f1
			}
			f2.QueryStringsConfig = f2f4
		}
		ko.Spec.OriginRequestPolicyConfig = f2
	} else {
		ko.Spec.OriginRequestPolicyConfig = nil
	}

	rm.setStatusDefaults(ko)
	// We need to do this manually because the ETag field (required for the
	// IfMatch field when updating or deleting a resource in CloudFront) is
	// outside the wrapper field of `OriginRequestPolicy` in the response
	// and therefore not picked up by SetResource code generation.
	if resp.ETag != nil {
		ko.Status.ETag = resp.ETag
	}

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateOriginRequestPolicyInput, error) {
	res := &svcsdk.CreateOriginRequestPolicyInput{}

	if r.ko.Spec.OriginRequestPolicyConfig != nil {
		f0 := &svcsdk.OriginRequestPolicyConfig{}
		if r.ko.Spec.OriginRequestPolicyConfig.Comment != nil {
			f0.SetComment(*r.ko.Spec.OriginRequestPolicyConfig.Comment)
		}
		if r.ko.Spec.OriginRequestPolicyConfig.CookiesConfig != nil {
			f0f1 := &svcsdk.OriginRequestPolicyCookiesConfig{}
			if r.ko.Spec.OriginRequestPolicyConfig.CookiesConfig.CookieBehavior != nil {
				f0f1.SetCookieBehavior(*r.ko.Spec.OriginRequestPolicyConfig.CookiesConfig.CookieBehavior)
			}
			if r.ko.Spec.OriginRequestPolicyConfig.CookiesConfig.Cookies != nil {
				f0f1f1 := &svcsdk.CookieNames{}
				if r.ko.Spec.OriginRequestPolicyConfig.CookiesConfig.Cookies.Items != nil {
					f0f1f1f0 := []*string{}
					for _, f0f1f1f0iter := range r.ko.Spec.OriginRequestPolicyConfig.CookiesConfig.Cookies.Items {
						var f0f1f1f0elem string
						f0f1f1f0elem = *f0f1f1f0iter
						f0f1f1f0 = append(f0f1f1f0, &f0f1f1f0elem)
					}
					f0f1f1.SetItems(f0f1f1f0)
				}
				f0f1.SetCookies(f0f1f1)
			}
			f0.SetCookiesConfig(f0f1)
		}
		if r.ko.Spec.OriginRequestPolicyConfig.HeadersConfig != nil {
			f0f2 := &svcsdk.OriginRequestPolicyHeadersConfig{}
			if r.ko.Spec.OriginRequestPolicyConfig.HeadersConfig.HeaderBehavior != nil {
				f0f2.SetHeaderBehavior(*r.ko.Spec.OriginRequestPolicyConfig.HeadersConfig.HeaderBehavior)
			}
			if r.ko.Spec.OriginRequestPolicyConfig.HeadersConfig.Headers != nil {
				f0f2f1 := &svcsdk.Headers{}
				if r.ko.Spec.OriginRequestPolicyConfig.HeadersConfig.Headers.Items != nil {
					f0f2f1f0 := []*string{}
					for _, f0f2f1f0iter := range r.ko.Spec.OriginRequestPolicyConfig.HeadersConfig.Headers.Items {
						var f0f2f1f0elem string
						f0f2f1f0elem = *f0f2f1f0iter
						f0f2f1f0 = append(f0f2f1f0, &f0f2f1f0elem)
					}
					f0f2f1.SetItems(f0f2f1f0)
				}
				f0f2.SetHeaders(f0f2f1)
			}
			f0.SetHeadersConfig(f0f2)
		}
		if r.ko.Spec.OriginRequestPolicyConfig.Name != nil {
			f0.SetName(*r.ko.Spec.OriginRequestPolicyConfig.Name)
		}
		if r.ko.Spec.OriginRequestPolicyConfig.QueryStringsConfig != nil {
			f0f4 := &svcsdk.OriginRequestPolicyQueryStringsConfig{}
			if r.ko.Spec.OriginRequestPolicyConfig.QueryStringsConfig.QueryStringBehavior != nil {
				f0f4.SetQueryStringBehavior(*r.ko.Spec.OriginRequestPolicyConfig.QueryStringsConfig.QueryStringBehavior)
			}
			if r.ko.Spec.OriginRequestPolicyConfig.QueryStringsConfig.QueryStrings != nil {
				f0f4f1 := &svcsdk.QueryStringNames{}
				if r.ko.Spec.OriginRequestPolicyConfig.QueryStringsConfig.QueryStrings.Items != nil {
					f0f4f1f0 := []*string{}
					for _, f0f4f1f0iter := range r.ko.Spec.OriginRequestPolicyConfig.QueryStringsConfig.QueryStrings.Items {
						var f0f4f1f0elem string
						f0f4f1f0elem = *f0f4f1f0iter
						f0f4f1f0 = append(f0f4f1f0, &f0f4f1f0elem)
					}
					f0f4f1.SetItems(f0f4f1f0)
				}
				f0f4.SetQueryStrings(f0f4f1)
			}
			f0.SetQueryStringsConfig(f0f4)
		}
		res.SetOriginRequestPolicyConfig(f0)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}
	// If we don't do this, we get the following on every update call:
	// InvalidIfMatchVersion: The If-Match version is missing or not valid for the resource.
	if latest.ko.Status.ETag != nil {
		input.SetIfMatch(*latest.ko.Status.ETag)
	}
	// ¯\\\_(ツ)_/¯
	setQuantityFields(input.OriginRequestPolicyConfig)

	var resp *svcsdk.UpdateOriginRequestPolicyOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateOriginRequestPolicyWithContext(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateOriginRequestPolicy", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.ETag != nil {
		ko.Status.ETag = resp.ETag
	} else {
		ko.Status.ETag = nil
	}

	rm.setStatusDefaults(ko)
	// We need to do this manually because the ETag field (required for the
	// IfMatch field when updating or deleting a resource in CloudFront) is
	// outside the wrapper field of `OriginRequestPolicy` in the response and
	// therefore not picked up by SetResource code generation.
	if resp.ETag != nil {
		ko.Status.ETag = resp.ETag
	}

	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateOriginRequestPolicyInput, error) {
	res := &svcsdk.UpdateOriginRequestPolicyInput{}

	if r.ko.Status.ID != nil {
		res.SetId(*r.ko.Status.ID)
	}
	if r.ko.Spec.OriginRequestPolicyConfig != nil {
		f2 := &svcsdk.OriginRequestPolicyConfig{}
		if r.ko.Spec.OriginRequestPolicyConfig.Comment != nil {
			f2.SetComment(*r.ko.Spec.OriginRequestPolicyConfig.Comment)
		}
		if r.ko.Spec.OriginRequestPolicyConfig.CookiesConfig != nil {
			f2f1 := &svcsdk.OriginRequestPolicyCookiesConfig{}
			if r.ko.Spec.OriginRequestPolicyConfig.CookiesConfig.CookieBehavior != nil {
				f2f1.SetCookieBehavior(*r.ko.Spec.OriginRequestPolicyConfig.CookiesConfig.CookieBehavior)
			}
			if r.ko.Spec.OriginRequestPolicyConfig.CookiesConfig.Cookies != nil {
				f2f1f1 := &svcsdk.CookieNames{}
				if r.ko.Spec.OriginRequestPolicyConfig.CookiesConfig.Cookies.Items != nil {
					f2f1f1f0 := []*string{}
					for _, f2f1f1f0iter := range r.ko.Spec.OriginRequestPolicyConfig.CookiesConfig.Cookies.Items {
						var f2f1f1f0elem string
						f2f1f1f0elem = *f2f1f1f0iter
						f2f1f1f0 = append(f2f1f1f0, &f2f1f1f0elem)
					}
					f2f1f1.SetItems(f2f1f1f0)
				}
				f2f1.SetCookies(f2f1f1)
			}
			f2.SetCookiesConfig(f2f1)
		}
		if r.ko.Spec.OriginRequestPolicyConfig.HeadersConfig != nil {
			f2f2 := &svcsdk.OriginRequestPolicyHeadersConfig{}
			if r.ko.Spec.OriginRequestPolicyConfig.HeadersConfig.HeaderBehavior != nil {
				f2f2.SetHeaderBehavior(*r.ko.Spec.OriginRequestPolicyConfig.HeadersConfig.HeaderBehavior)
			}
			if r.ko.Spec.OriginRequestPolicyConfig.HeadersConfig.Headers != nil {
				f2f2f1 := &svcsdk.Headers{}
				if r.ko.Spec.OriginRequestPolicyConfig.HeadersConfig.Headers.Items != nil {
					f2f2f1f0 := []*string{}
					for _, f2f2f1f0iter := range r.ko.Spec.OriginRequestPolicyConfig.HeadersConfig.Headers.Items {
						var f2f2f1f0elem string
						f2f2f1f0elem = *f2f2f1f0iter
						f2f2f1f0 = append(f2f2f1f0, &f2f2f1f0elem)
					}
					f2f2f1.SetItems(f2f2f1f0)
				}
				f2f2.SetHeaders(f2f2f1)
			}
			f2.SetHeadersConfig(f2f2)
		}
		if r.ko.Spec.OriginRequestPolicyConfig.Name != nil {
			f2.SetName(*r.ko.Spec.OriginRequestPolicyConfig.Name)
		}
		if r.ko.Spec.OriginRequestPolicyConfig.QueryStringsConfig != nil {
			f2f4 := &svcsdk.OriginRequestPolicyQueryStringsConfig{}
			if r.ko.Spec.OriginRequestPolicyConfig.QueryStringsConfig.QueryStringBehavior != nil {
				f2f4.SetQueryStringBehavior(*r.ko.Spec.OriginRequestPolicyConfig.QueryStringsConfig.QueryStringBehavior)
			}
			if r.ko.Spec.OriginRequestPolicyConfig.QueryStringsConfig.QueryStrings != nil {
				f2f4f1 := &svcsdk.QueryStringNames{}
				if r.ko.Spec.OriginRequestPolicyConfig.QueryStringsConfig.QueryStrings.Items != nil {
					f2f4f1f0 := []*string{}
					for _, f2f4f1f0iter := range r.ko.Spec.OriginRequestPolicyConfig.QueryStringsConfig.QueryStrings.Items {
						var f2f4f1f0elem string
						f2f4f1f0elem = *f2f4f1f0iter
						f2f4f1f0 = append(f2f4f1f0, &f2f4f1f0elem)
					}
					f2f4f1.SetItems(f2f4f1f0)
				}
				f2f4.SetQueryStrings(f2f4f1)
			}
			f2.SetQueryStringsConfig(f2f4)
		}
		res.SetOriginRequestPolicyConfig(f2)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	// If we don't do this, we get the following on every delete call:
	// InvalidIfMatchVersion: The If-Match version is missing or not valid for the resource.
	if r.ko.Status.ETag != nil {
		input.SetIfMatch(*r.ko.Status.ETag)
	}

	var resp *svcsdk.DeleteOriginRequestPolicyOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteOriginRequestPolicyWithContext(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteOriginRequestPolicy", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteOriginRequestPolicyInput, error) {
	res := &svcsdk.DeleteOriginRequestPolicyInput{}

	if r.ko.Status.ID != nil {
		res.SetId(*r.ko.Status.ID)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.OriginRequestPolicy,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
