// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package distribution_tenant

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.ConnectionGroupID, b.ko.Spec.ConnectionGroupID) {
		delta.Add("Spec.ConnectionGroupID", a.ko.Spec.ConnectionGroupID, b.ko.Spec.ConnectionGroupID)
	} else if a.ko.Spec.ConnectionGroupID != nil && b.ko.Spec.ConnectionGroupID != nil {
		if *a.ko.Spec.ConnectionGroupID != *b.ko.Spec.ConnectionGroupID {
			delta.Add("Spec.ConnectionGroupID", a.ko.Spec.ConnectionGroupID, b.ko.Spec.ConnectionGroupID)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.ConnectionGroupRef, b.ko.Spec.ConnectionGroupRef) {
		delta.Add("Spec.ConnectionGroupRef", a.ko.Spec.ConnectionGroupRef, b.ko.Spec.ConnectionGroupRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Customizations, b.ko.Spec.Customizations) {
		delta.Add("Spec.Customizations", a.ko.Spec.Customizations, b.ko.Spec.Customizations)
	} else if a.ko.Spec.Customizations != nil && b.ko.Spec.Customizations != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Customizations.Certificate, b.ko.Spec.Customizations.Certificate) {
			delta.Add("Spec.Customizations.Certificate", a.ko.Spec.Customizations.Certificate, b.ko.Spec.Customizations.Certificate)
		} else if a.ko.Spec.Customizations.Certificate != nil && b.ko.Spec.Customizations.Certificate != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.Customizations.Certificate.ARN, b.ko.Spec.Customizations.Certificate.ARN) {
				delta.Add("Spec.Customizations.Certificate.ARN", a.ko.Spec.Customizations.Certificate.ARN, b.ko.Spec.Customizations.Certificate.ARN)
			} else if a.ko.Spec.Customizations.Certificate.ARN != nil && b.ko.Spec.Customizations.Certificate.ARN != nil {
				if *a.ko.Spec.Customizations.Certificate.ARN != *b.ko.Spec.Customizations.Certificate.ARN {
					delta.Add("Spec.Customizations.Certificate.ARN", a.ko.Spec.Customizations.Certificate.ARN, b.ko.Spec.Customizations.Certificate.ARN)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.Customizations.GeoRestrictions, b.ko.Spec.Customizations.GeoRestrictions) {
			delta.Add("Spec.Customizations.GeoRestrictions", a.ko.Spec.Customizations.GeoRestrictions, b.ko.Spec.Customizations.GeoRestrictions)
		} else if a.ko.Spec.Customizations.GeoRestrictions != nil && b.ko.Spec.Customizations.GeoRestrictions != nil {
			if len(a.ko.Spec.Customizations.GeoRestrictions.Locations) != len(b.ko.Spec.Customizations.GeoRestrictions.Locations) {
				delta.Add("Spec.Customizations.GeoRestrictions.Locations", a.ko.Spec.Customizations.GeoRestrictions.Locations, b.ko.Spec.Customizations.GeoRestrictions.Locations)
			} else if len(a.ko.Spec.Customizations.GeoRestrictions.Locations) > 0 {
				if !ackcompare.SliceStringPEqual(a.ko.Spec.Customizations.GeoRestrictions.Locations, b.ko.Spec.Customizations.GeoRestrictions.Locations) {
					delta.Add("Spec.Customizations.GeoRestrictions.Locations", a.ko.Spec.Customizations.GeoRestrictions.Locations, b.ko.Spec.Customizations.GeoRestrictions.Locations)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Customizations.GeoRestrictions.RestrictionType, b.ko.Spec.Customizations.GeoRestrictions.RestrictionType) {
				delta.Add("Spec.Customizations.GeoRestrictions.RestrictionType", a.ko.Spec.Customizations.GeoRestrictions.RestrictionType, b.ko.Spec.Customizations.GeoRestrictions.RestrictionType)
			} else if a.ko.Spec.Customizations.GeoRestrictions.RestrictionType != nil && b.ko.Spec.Customizations.GeoRestrictions.RestrictionType != nil {
				if *a.ko.Spec.Customizations.GeoRestrictions.RestrictionType != *b.ko.Spec.Customizations.GeoRestrictions.RestrictionType {
					delta.Add("Spec.Customizations.GeoRestrictions.RestrictionType", a.ko.Spec.Customizations.GeoRestrictions.RestrictionType, b.ko.Spec.Customizations.GeoRestrictions.RestrictionType)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.Customizations.WebACL, b.ko.Spec.Customizations.WebACL) {
			delta.Add("Spec.Customizations.WebACL", a.ko.Spec.Customizations.WebACL, b.ko.Spec.Customizations.WebACL)
		} else if a.ko.Spec.Customizations.WebACL != nil && b.ko.Spec.Customizations.WebACL != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.Customizations.WebACL.Action, b.ko.Spec.Customizations.WebACL.Action) {
				delta.Add("Spec.Customizations.WebACL.Action", a.ko.Spec.Customizations.WebACL.Action, b.ko.Spec.Customizations.WebACL.Action)
			} else if a.ko.Spec.Customizations.WebACL.Action != nil && b.ko.Spec.Customizations.WebACL.Action != nil {
				if *a.ko.Spec.Customizations.WebACL.Action != *b.ko.Spec.Customizations.WebACL.Action {
					delta.Add("Spec.Customizations.WebACL.Action", a.ko.Spec.Customizations.WebACL.Action, b.ko.Spec.Customizations.WebACL.Action)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Customizations.WebACL.ARN, b.ko.Spec.Customizations.WebACL.ARN) {
				delta.Add("Spec.Customizations.WebACL.ARN", a.ko.Spec.Customizations.WebACL.ARN, b.ko.Spec.Customizations.WebACL.ARN)
			} else if a.ko.Spec.Customizations.WebACL.ARN != nil && b.ko.Spec.Customizations.WebACL.ARN != nil {
				if *a.ko.Spec.Customizations.WebACL.ARN != *b.ko.Spec.Customizations.WebACL.ARN {
					delta.Add("Spec.Customizations.WebACL.ARN", a.ko.Spec.Customizations.WebACL.ARN, b.ko.Spec.Customizations.WebACL.ARN)
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DistributionID, b.ko.Spec.DistributionID) {
		delta.Add("Spec.DistributionID", a.ko.Spec.DistributionID, b.ko.Spec.DistributionID)
	} else if a.ko.Spec.DistributionID != nil && b.ko.Spec.DistributionID != nil {
		if *a.ko.Spec.DistributionID != *b.ko.Spec.DistributionID {
			delta.Add("Spec.DistributionID", a.ko.Spec.DistributionID, b.ko.Spec.DistributionID)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.DistributionRef, b.ko.Spec.DistributionRef) {
		delta.Add("Spec.DistributionRef", a.ko.Spec.DistributionRef, b.ko.Spec.DistributionRef)
	}
	if len(a.ko.Spec.Domains) != len(b.ko.Spec.Domains) {
		delta.Add("Spec.Domains", a.ko.Spec.Domains, b.ko.Spec.Domains)
	} else if len(a.ko.Spec.Domains) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Domains, b.ko.Spec.Domains) {
			delta.Add("Spec.Domains", a.ko.Spec.Domains, b.ko.Spec.Domains)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Enabled, b.ko.Spec.Enabled) {
		delta.Add("Spec.Enabled", a.ko.Spec.Enabled, b.ko.Spec.Enabled)
	} else if a.ko.Spec.Enabled != nil && b.ko.Spec.Enabled != nil {
		if *a.ko.Spec.Enabled != *b.ko.Spec.Enabled {
			delta.Add("Spec.Enabled", a.ko.Spec.Enabled, b.ko.Spec.Enabled)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ManagedCertificateRequest, b.ko.Spec.ManagedCertificateRequest) {
		delta.Add("Spec.ManagedCertificateRequest", a.ko.Spec.ManagedCertificateRequest, b.ko.Spec.ManagedCertificateRequest)
	} else if a.ko.Spec.ManagedCertificateRequest != nil && b.ko.Spec.ManagedCertificateRequest != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.ManagedCertificateRequest.CertificateTransparencyLoggingPreference, b.ko.Spec.ManagedCertificateRequest.CertificateTransparencyLoggingPreference) {
			delta.Add("Spec.ManagedCertificateRequest.CertificateTransparencyLoggingPreference", a.ko.Spec.ManagedCertificateRequest.CertificateTransparencyLoggingPreference, b.ko.Spec.ManagedCertificateRequest.CertificateTransparencyLoggingPreference)
		} else if a.ko.Spec.ManagedCertificateRequest.CertificateTransparencyLoggingPreference != nil && b.ko.Spec.ManagedCertificateRequest.CertificateTransparencyLoggingPreference != nil {
			if *a.ko.Spec.ManagedCertificateRequest.CertificateTransparencyLoggingPreference != *b.ko.Spec.ManagedCertificateRequest.CertificateTransparencyLoggingPreference {
				delta.Add("Spec.ManagedCertificateRequest.CertificateTransparencyLoggingPreference", a.ko.Spec.ManagedCertificateRequest.CertificateTransparencyLoggingPreference, b.ko.Spec.ManagedCertificateRequest.CertificateTransparencyLoggingPreference)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.ManagedCertificateRequest.PrimaryDomainName, b.ko.Spec.ManagedCertificateRequest.PrimaryDomainName) {
			delta.Add("Spec.ManagedCertificateRequest.PrimaryDomainName", a.ko.Spec.ManagedCertificateRequest.PrimaryDomainName, b.ko.Spec.ManagedCertificateRequest.PrimaryDomainName)
		} else if a.ko.Spec.ManagedCertificateRequest.PrimaryDomainName != nil && b.ko.Spec.ManagedCertificateRequest.PrimaryDomainName != nil {
			if *a.ko.Spec.ManagedCertificateRequest.PrimaryDomainName != *b.ko.Spec.ManagedCertificateRequest.PrimaryDomainName {
				delta.Add("Spec.ManagedCertificateRequest.PrimaryDomainName", a.ko.Spec.ManagedCertificateRequest.PrimaryDomainName, b.ko.Spec.ManagedCertificateRequest.PrimaryDomainName)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.ManagedCertificateRequest.ValidationTokenHost, b.ko.Spec.ManagedCertificateRequest.ValidationTokenHost) {
			delta.Add("Spec.ManagedCertificateRequest.ValidationTokenHost", a.ko.Spec.ManagedCertificateRequest.ValidationTokenHost, b.ko.Spec.ManagedCertificateRequest.ValidationTokenHost)
		} else if a.ko.Spec.ManagedCertificateRequest.ValidationTokenHost != nil && b.ko.Spec.ManagedCertificateRequest.ValidationTokenHost != nil {
			if *a.ko.Spec.ManagedCertificateRequest.ValidationTokenHost != *b.ko.Spec.ManagedCertificateRequest.ValidationTokenHost {
				delta.Add("Spec.ManagedCertificateRequest.ValidationTokenHost", a.ko.Spec.ManagedCertificateRequest.ValidationTokenHost, b.ko.Spec.ManagedCertificateRequest.ValidationTokenHost)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if len(a.ko.Spec.Parameters) != len(b.ko.Spec.Parameters) {
		delta.Add("Spec.Parameters", a.ko.Spec.Parameters, b.ko.Spec.Parameters)
	} else if len(a.ko.Spec.Parameters) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Parameters, b.ko.Spec.Parameters) {
			delta.Add("Spec.Parameters", a.ko.Spec.Parameters, b.ko.Spec.Parameters)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
