// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package function

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if !bytes.Equal(a.ko.Spec.FunctionCode, b.ko.Spec.FunctionCode) {
		delta.Add("Spec.FunctionCode", a.ko.Spec.FunctionCode, b.ko.Spec.FunctionCode)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.FunctionConfig, b.ko.Spec.FunctionConfig) {
		delta.Add("Spec.FunctionConfig", a.ko.Spec.FunctionConfig, b.ko.Spec.FunctionConfig)
	} else if a.ko.Spec.FunctionConfig != nil && b.ko.Spec.FunctionConfig != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.FunctionConfig.Comment, b.ko.Spec.FunctionConfig.Comment) {
			delta.Add("Spec.FunctionConfig.Comment", a.ko.Spec.FunctionConfig.Comment, b.ko.Spec.FunctionConfig.Comment)
		} else if a.ko.Spec.FunctionConfig.Comment != nil && b.ko.Spec.FunctionConfig.Comment != nil {
			if *a.ko.Spec.FunctionConfig.Comment != *b.ko.Spec.FunctionConfig.Comment {
				delta.Add("Spec.FunctionConfig.Comment", a.ko.Spec.FunctionConfig.Comment, b.ko.Spec.FunctionConfig.Comment)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.FunctionConfig.Runtime, b.ko.Spec.FunctionConfig.Runtime) {
			delta.Add("Spec.FunctionConfig.Runtime", a.ko.Spec.FunctionConfig.Runtime, b.ko.Spec.FunctionConfig.Runtime)
		} else if a.ko.Spec.FunctionConfig.Runtime != nil && b.ko.Spec.FunctionConfig.Runtime != nil {
			if *a.ko.Spec.FunctionConfig.Runtime != *b.ko.Spec.FunctionConfig.Runtime {
				delta.Add("Spec.FunctionConfig.Runtime", a.ko.Spec.FunctionConfig.Runtime, b.ko.Spec.FunctionConfig.Runtime)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}

	return delta
}
